#!/bin/sh

echo "Performing tests..."
./gradlew -q test; gradlew_return_code=$?

if (( gradlew_return_code != 0 )); then
  echo "✘ Your unit tests have failed, please check them."
  echo "ⓘ You can view the test results at build/reports/tests/test/index.html"
  exit 1
else
  echo "✓ GG we can commit your code."
fi
