#!/bin/sh

echo "Checking if the code is formatted..."
./gradlew -q spotlessCheck; gradlew_return_code=$?

if (( gradlew_return_code != 0 )); then
  echo "✘ You're a delulu if you think this code can be commited."
  echo "ⓘ Run ./gradlew spotlessApply and then try to commit again."
  exit 1
else
  echo "✓ Big W your code is goated."
fi

echo ""

# Download missing files that are needed in order for wpilib to perform unit tests
if [[ "$OSTYPE" == "msys" ]]; then
  if [ ! -f C:\Users\Public\wpilib\2024\maven\org\junit\jupiter\junit-jupiter\5.10.1\junit-jupiter-5.10.1.module ]; then
    pwsh -c "Invoke-WebRequest -Uri https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter/5.10.1/junit-jupiter-5.10.1.module -OutFile C:\Users\Public\wpilib\2024\maven\org\junit\jupiter\junit-jupiter\5.10.1\junit-jupiter-5.10.1.module"
  fi
  if [ ! -f C:\Users\Public\wpilib\2024\maven\org\junit\junit-bom\5.10.1\junit-bom-5.10.1.module ]; then
    pwsh -c "Invoke-WebRequest -Uri https://repo.maven.apache.org/maven2/org/junit/junit-bom/5.10.1/junit-bom-5.10.1.module -OutFile C:\Users\Public\wpilib\2024\maven\org\junit\junit-bom\5.10.1\junit-bom-5.10.1.module"
  fi
else
  if [ ! -f ~/wpilib/2024/maven/org/junit/jupiter/junit-jupiter/5.10.1/junit-jupiter-5.10.1.module ]; then
    curl https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter/5.10.1/junit-jupiter-5.10.1.module -o ~/wpilib/2024/maven/org/junit/jupiter/junit-jupiter/5.10.1/junit-jupiter-5.10.1.module
  fi
  if [ ! -f ~/wpilib/2024/maven/org/junit/junit-bom/5.10.1/junit-bom-5.10.1.module ]; then
    curl https://repo.maven.apache.org/maven2/org/junit/junit-bom/5.10.1/junit-bom-5.10.1.module -o ~/wpilib/2024/maven/org/junit/junit-bom/5.10.1/junit-bom-5.10.1.module
  fi
fi

echo "Performing tests..."
./gradlew -q test; gradlew_return_code=$?

if (( gradlew_return_code != 0 )); then
  echo "✘ Your skibidi unit tests have failed, please check them before commiting again."
  echo "ⓘ You can view the test results at build/reports/tests/test/index.html"
  exit 1
else
  echo "✓ GG! You have so much rizz, we can commit your code."
fi
